"""Phone<->backend wire contract (WebSocket + REST)."""

from studentassistant.protocol.audio import (
    HEADER_SIZE,
    MAGIC,
    AudioFrame,
    AudioFrameError,
    IncompatibleAudioFrameVersionError,
    WrongMagicError,
    decode_frame,
    encode_frame,
)
from studentassistant.protocol.base import ProtocolModel
from studentassistant.protocol.client import (
    CLIENT_EVENT_ADAPTER,
    AudioFormat,
    Button,
    ClientAck,
    ClientCapabilities,
    ClientEvent,
    ClientHello,
    Marker,
    TranscriptClientFinal,
    TranscriptClientPartial,
    parse_client_event,
)
from studentassistant.protocol.errors import ERROR_CODE_SINCE, ErrorCode
from studentassistant.protocol.registry import MODELS, model_for
from studentassistant.protocol.rest import (
    DIGEST_EXCERPT_MAX,
    CaptureImage,
    CaptureUploadRequest,
    CaptureUploadResponse,
    HealthResponse,
    PairRequest,
    PairResponse,
    SearchHit,
    SearchResponse,
    Session,
    SessionEndRequest,
    SessionEndResponse,
    SessionStartRequest,
    Subject,
    SubjectCreateRequest,
    SubjectsListResponse,
    Topic,
    TopicCreateRequest,
    TopicsListResponse,
)
from studentassistant.protocol.server import (
    SERVER_EVENT_ADAPTER,
    Command,
    HelloAck,
    Notice,
    ServerAck,
    ServerEvent,
    TranscriptFinal,
    TranscriptPartial,
    parse_server_event,
)
from studentassistant.protocol.version import (
    PROTOCOL_VERSION,
    IncompatibleProtocolVersionError,
    check_compatible,
    negotiate,
    parse_version,
)

__all__ = [
    "CLIENT_EVENT_ADAPTER",
    "DIGEST_EXCERPT_MAX",
    "ERROR_CODE_SINCE",
    "HEADER_SIZE",
    "MAGIC",
    "MODELS",
    "PROTOCOL_VERSION",
    "SERVER_EVENT_ADAPTER",
    "AudioFormat",
    "AudioFrame",
    "AudioFrameError",
    "Button",
    "CaptureImage",
    "CaptureUploadRequest",
    "CaptureUploadResponse",
    "ClientAck",
    "ClientCapabilities",
    "ClientEvent",
    "ClientHello",
    "Command",
    "ErrorCode",
    "HealthResponse",
    "HelloAck",
    "IncompatibleAudioFrameVersionError",
    "IncompatibleProtocolVersionError",
    "Marker",
    "Notice",
    "PairRequest",
    "PairResponse",
    "SearchHit",
    "SearchResponse",
    "ProtocolModel",
    "ServerAck",
    "ServerEvent",
    "Session",
    "SessionEndRequest",
    "SessionEndResponse",
    "SessionStartRequest",
    "Subject",
    "SubjectCreateRequest",
    "SubjectsListResponse",
    "Topic",
    "TopicCreateRequest",
    "TopicsListResponse",
    "TranscriptClientFinal",
    "TranscriptClientPartial",
    "TranscriptFinal",
    "TranscriptPartial",
    "WrongMagicError",
    "check_compatible",
    "decode_frame",
    "encode_frame",
    "model_for",
    "negotiate",
    "parse_client_event",
    "parse_server_event",
    "parse_version",
]
