"""Phone<->backend wire contract (WebSocket + REST)."""

from studentassistant.protocol.base import ProtocolModel
from studentassistant.protocol.client import (
    CLIENT_EVENT_ADAPTER,
    AudioFormat,
    Button,
    ClientAck,
    ClientCapabilities,
    ClientEvent,
    ClientHello,
    Marker,
    TranscriptClientFinal,
    TranscriptClientPartial,
    parse_client_event,
)
from studentassistant.protocol.registry import MODELS, model_for
from studentassistant.protocol.rest import (
    CaptureImage,
    CaptureUploadRequest,
    CaptureUploadResponse,
    HealthResponse,
    PairRequest,
    PairResponse,
    Session,
    SessionEndRequest,
    SessionEndResponse,
    SessionStartRequest,
    Subject,
    SubjectCreateRequest,
    SubjectsListResponse,
    Topic,
    TopicCreateRequest,
    TopicsListResponse,
)
from studentassistant.protocol.server import (
    SERVER_EVENT_ADAPTER,
    Command,
    HelloAck,
    Notice,
    ServerAck,
    ServerEvent,
    TranscriptFinal,
    TranscriptPartial,
    parse_server_event,
)
from studentassistant.protocol.version import (
    PROTOCOL_VERSION,
    IncompatibleProtocolVersionError,
    check_compatible,
    negotiate,
    parse_version,
)

__all__ = [
    "CLIENT_EVENT_ADAPTER",
    "MODELS",
    "PROTOCOL_VERSION",
    "SERVER_EVENT_ADAPTER",
    "AudioFormat",
    "Button",
    "CaptureImage",
    "CaptureUploadRequest",
    "CaptureUploadResponse",
    "ClientAck",
    "ClientCapabilities",
    "ClientEvent",
    "ClientHello",
    "Command",
    "HealthResponse",
    "HelloAck",
    "IncompatibleProtocolVersionError",
    "Marker",
    "Notice",
    "PairRequest",
    "PairResponse",
    "ProtocolModel",
    "ServerAck",
    "ServerEvent",
    "Session",
    "SessionEndRequest",
    "SessionEndResponse",
    "SessionStartRequest",
    "Subject",
    "SubjectCreateRequest",
    "SubjectsListResponse",
    "Topic",
    "TopicCreateRequest",
    "TopicsListResponse",
    "TranscriptClientFinal",
    "TranscriptClientPartial",
    "TranscriptFinal",
    "TranscriptPartial",
    "check_compatible",
    "model_for",
    "negotiate",
    "parse_client_event",
    "parse_server_event",
    "parse_version",
]
