"""Git-backed content store: layout, writers, commit/push/pull, setup, SQLite index."""

from studentassistant.vault.git import GitCommandError, GitIdentity, GitResult, GitRunner
from studentassistant.vault.jsonl import JsonlError, append_jsonl, last_seq, read_jsonl
from studentassistant.vault.ledger import (
    LedgerEntry,
    LedgerError,
    append_ledger_entry,
    ledger_path,
    read_all_ledgers,
    read_ledger,
)
from studentassistant.vault.secrets import SecretRefused, guard, looks_like_secret
from studentassistant.vault.session_models import (
    EVENT_SCHEMA_VERSION,
    Event,
    SessionMeta,
    TranscriptSegment,
    TranscriptWord,
)
from studentassistant.vault.sessions import (
    NoOpenSessionError,
    Session,
    SessionEndedError,
    SessionError,
    SessionFileError,
    end_session,
    resume_session,
    sessions_directory,
    start_session,
)
from studentassistant.vault.sources import (
    SOURCE_KINDS,
    SourceError,
    UnknownSourceKindError,
    put_source,
    sources_directory,
)
from studentassistant.vault.subjects import (
    StoredSubject,
    SubjectError,
    SubjectFileError,
    SubjectNotFoundError,
    create_subject,
    get_subject,
    list_subjects,
    subject_directory,
)
from studentassistant.vault.sync import (
    Clock,
    GitSync,
    NotesTag,
    PushFailure,
    SyncResult,
    SyncStatus,
    SystemClock,
    notes_tag_name,
)
from studentassistant.vault.topics import (
    StoredTopic,
    TopicError,
    TopicFileError,
    TopicNotFoundError,
    create_topic,
    get_topic,
    list_topics,
    topic_directory,
    topics_directory,
)
from studentassistant.vault.vault import (
    Vault,
    VaultError,
    VaultFormatError,
    VaultMetaError,
    VaultNotFoundError,
)

__all__ = [
    "EVENT_SCHEMA_VERSION",
    "SOURCE_KINDS",
    "Clock",
    "Event",
    "GitCommandError",
    "GitIdentity",
    "GitResult",
    "GitRunner",
    "GitSync",
    "JsonlError",
    "LedgerEntry",
    "LedgerError",
    "NoOpenSessionError",
    "NotesTag",
    "PushFailure",
    "SecretRefused",
    "Session",
    "SessionEndedError",
    "SessionError",
    "SessionFileError",
    "SessionMeta",
    "SourceError",
    "StoredSubject",
    "StoredTopic",
    "SubjectError",
    "SubjectFileError",
    "SubjectNotFoundError",
    "SyncResult",
    "SyncStatus",
    "SystemClock",
    "TopicError",
    "TopicFileError",
    "TopicNotFoundError",
    "TranscriptSegment",
    "TranscriptWord",
    "UnknownSourceKindError",
    "Vault",
    "VaultError",
    "VaultFormatError",
    "VaultMetaError",
    "VaultNotFoundError",
    "append_jsonl",
    "append_ledger_entry",
    "create_subject",
    "create_topic",
    "end_session",
    "get_subject",
    "get_topic",
    "guard",
    "last_seq",
    "ledger_path",
    "list_subjects",
    "list_topics",
    "looks_like_secret",
    "notes_tag_name",
    "put_source",
    "read_all_ledgers",
    "read_jsonl",
    "read_ledger",
    "resume_session",
    "sessions_directory",
    "sources_directory",
    "start_session",
    "subject_directory",
    "topic_directory",
    "topics_directory",
]
